[theme2]
primaryColor="#fdc57b"
backgroundColor="#fbf2d5"
secondaryBackgroundColor="#7fa99b"
textColor="#394a51"

[theme]
primaryColor="#ffa952"
backgroundColor="#feffdf"
secondaryBackgroundColor="#ffe79a"
textColor="#24527a"