[[pages]]
name = "Funnel Analysis"
icon = "📊"
is_section = true

[[pages]]
path = "app_pages/single_funnel.py"
name = "Single Funnel"
icon = "🔽"

[[pages]]
path = "app_pages/compare_funnels.py"
name = "Compare App Funnels"
icon = "↔️"

[[pages]]
path = "app_pages/sideways_funnel.py"
name = "Sideways Funnel by Language"
icon = "🌐"

[[pages]]
path = "app_pages/best_languages.py"
name = "Top/Bottom Performing Languages"
icon = "🏆"

[[pages]]
name = "Metrics"
icon = "📈"
is_section = true

[[pages]]
path = "app_pages/time_to_ra.py"
name = "Readers Acquired"
icon = "⭐"

[[pages]]
path = "app_pages/levels_reached.py"
name = "Levels"
icon = "🎯"

[[pages]]
path = "app_pages/acquisition.py"
name = "Acquisition"
icon = "📥"

[[pages]]
path = "app_pages/difficulty_by_language.py"
name = "Language Difficulty"
icon = "🧠"

[[pages]]
path = "app_pages/marketing_data.py"
name = "Marketing Data"
icon = "📣"

[[pages]]
name = "Books"
icon = "📚"
is_section = true

[[pages]]
path = "app_pages/books.py"
name = "Book Engagement Overview"
icon = "📖"

[[pages]]
path = "app_pages/book_details.py"
name = "Book Detail & Stickiness"
icon = "🔖"

[[pages]]
name = "Users"
icon = "👥"
is_section = true

[[pages]]
path = "app_pages/user_details.py"
name = "User Lookup"
icon = "🔍"

[[pages]]
path = "app_pages/cohort_history.py"
name = "FTM Gameplay Timeline (Cohort Only)"
icon = "🎬"