
[[pages]]
name = "Funnel Analysis"
icon = ":large_brown_circle:"
is_section = true

[[pages]]
path = "app_pages/Unity_vs_CR.py"
name = "Unity vs Curious Reader Funnel"
icon = ":small_orange_diamond:"

[[pages]]
path = "app_pages/CR_Funnel.py"
name = "Curious Reader Funnel"
icon = ":small_orange_diamond:"

[[pages]]
path = "app_pages/20_Compare_Funnels.py"
name = "Compare CR Funnels"
icon = ":small_orange_diamond:"

[[pages]]
path = "app_pages/Funnel_Change.py"
name = "Funnel Change by Language"
icon = ":small_orange_diamond:"

[[pages]]
path = "app_pages/Sideways_Funnel.py"
name = "Sideways Funnel by Language"
icon = ":small_orange_diamond:"

[[pages]]
path = "app_pages/Best_Languages.py"
name = "Best and Worst Performing Languages"
icon = ":small_orange_diamond:"

[[pages]]
name = "Metrics"
icon = ":house:"
is_section = true

[[pages]]
path = "app_pages/time_to_ra.py"
name = "Time to Reach RA"
icon = ":small_orange_diamond:"

[[pages]]
path = "app_pages/levels_reached.py"
name = "Levels Reached"
icon = ":small_orange_diamond:"

[[pages]]
path = "app_pages/engagement_over_time.py"
name = "Engagement Over Time"
icon = ":small_orange_diamond:"

[[pages]]
path = "app_pages/unity_cr_engagement_metrics.py"
name = "Unity and CR Session Metrics"
icon = ":small_orange_diamond:"



[[pages]]
path = "app_pages/1_Acquisition.py"
name = "Acquisition"
icon = ":small_orange_diamond:"

[[pages]]
path = "app_pages/Marketing_Data.py"
name = "Marketing Data"
icon = ":small_orange_diamond:"


[[pages]]
name = "Users"
icon = ":large_brown_circle:"
is_section = true

[[pages]]
path = "app_pages/user_details.py"
name = "User Lookup"
icon = ":small_orange_diamond:"




