
[[pages]]
name = "Funnel Analysis"
icon = ":large_brown_circle:"
is_section = true

[[pages]]
path = "app_pages/compare_funnels.py"
name = "Compare App Funnels"
icon = ":small_orange_diamond:"

[[pages]]
path = "app_pages/single_funnel.py"
name = "Single Funnel"
icon = ":small_orange_diamond:"

[[pages]]
path = "app_pages/sideways_funnel.py"
name = "Sideways Funnel by Language"
icon = ":small_orange_diamond:"

[[pages]]
path = "app_pages/best_languages.py"
name = "Top/Bottom Performing Languages"
icon = ":small_orange_diamond:"

[[pages]]
name = "Metrics"
icon = ":house:"
is_section = true

[[pages]]
path = "app_pages/time_to_ra.py"
name = "Time to Reach RA"
icon = ":small_orange_diamond:"

[[pages]]
path = "app_pages/levels_reached.py"
name = "Levels Reached"
icon = ":small_orange_diamond:"


[[pages]]
path = "app_pages/acquisition.py"
name = "Acquisition"
icon = ":small_orange_diamond:"

[[pages]]
path = "app_pages/marketing_data.py"
name = "Marketing Data"
icon = ":small_orange_diamond:"

[[pages]]
name = "Users"
icon = ":large_brown_circle:"
is_section = true

[[pages]]
path = "app_pages/user_details.py"
name = "User Lookup"
icon = ":small_orange_diamond:"




